### ISSUE TITLE
Extrapolation of rel.perm. curves

### ISSUE THREAD

**Issue by laods** [OPM/opm-porsol#56]
Hi,

I have been digging into boundary conditions for steady-state upscaling. As I understand, for fixed BCs, the fractional flow is calculated on each boundary face not parallel to the flow direction (see opm/porsol/euler/EulerUpstreamImplicit_impl.hpp). However, I observe that for saturations outside the range of the input curves, the fractional flow is negative(!). Further digging tells me that the rel.perm in such regions are extrapolated using class Opm::NonuniformTableLinear, and this cause negative rel.perm. because the curve is strictly monotone. 

This has also caused me troubles in other settings as well, for instance 

    Assertion `! ((m[0] < 0) || (m[1] < 0))' failed.

in `opm/core/transport/implicit/SinglePointUpwindTwoPhase.hpp:385`. 

I think we all can agree that negative rel.perms are unfeasible (this also goes for rel.perm > 1). Thus extrapolation of rel.perm curves is dangerous. I am not sure how we best can handle this? Maybe set rel.perm. to 0 or 1 if out of range? Or include a check on the returned rel.perm, if it is in [0,1], and otherwise set it to 0 or 1?

**Comment by atgeirr** [comment]
While the question remains (extrapolate or not), it is not something we will reach a conclusion on, so I will close this issue. The particular system in question is used only for the upscaling codes, and may in a future refactoring be changed to share more parts with Flow, at that point we may see if different usage warrants different policies (but my guess is that it does not).
